#!/usr/bin/env python3
# -*- coding=utf-8 -*-

# 设置环境 code/version/buildVer.py

import os
import time
import secrets
import subprocess

buildVer_text = '''/**
 * @brief 编译信息
 * 本文件由buildVer.py自动生成
 * This file is automatically generated by buildver.py
 *
 * @file buildVer.h
 */
#pragma once

#define buildTime {buildTime}LL
#define buildSalt {buildSalt}
#define buildBranch "{buildBranch}"
#define buildSHA1 "{buildSHA1}"
'''

buildVer_dir = os.path.dirname(os.path.abspath(__file__))

buildTime = int(time.time())
buildSalt = secrets.randbits(31)
buildBranch = subprocess.run('git rev-parse --abbrev-ref HEAD', stdout=subprocess.PIPE, shell=True, cwd=buildVer_dir).stdout.decode('utf-8').strip()
buildSHA1 = subprocess.run('git rev-parse --short=7 HEAD', stdout=subprocess.PIPE, shell=True, cwd=buildVer_dir).stdout.decode('utf-8').strip()

with open(os.path.join(buildVer_dir, 'buildVer.h'), 'w', encoding='utf-8', newline='\n') as f:
    f.write(buildVer_text.format(buildTime=buildTime, buildSalt=buildSalt, buildBranch=buildBranch, buildSHA1=buildSHA1))

# export buildTime=$(date +%s)
# export buildSalt=$(date +1%6N)
# export buildBranch=$(git --git-dir $${PWD}/.git rev-parse --abbrev-ref HEAD)
# export buildSHA1=$(git --git-dir $${PWD}/.git rev-parse --short=7 HEAD)
