# Qt 自动化编译

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  APP: tx

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
      - name: info
        run: |
          echo "APP_TIME=$(date -u  +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "APP_SHA1=${${{github.sha}}:0:7}" >> $GITHUB_ENV

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{runner.os}}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.11"
          host: "linux"
          target: "desktop"
          cached: "${{steps.cache-qt.outputs.cache-hit}}"
          setup-python: "true"

      - name: checkout
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      - name: test
        run: |
          mkdir -p ${{github.workspace}}/build/test
          cd ${{github.workspace}}/build/test
          qmake APP_TEST=1 ${{github.workspace}}/${{env.APP}}.pro
          make -j$(nproc)
          make check

      - name: build release
        run: |
          mkdir -p ${{github.workspace}}/build/release
          cd ${{github.workspace}}/build/release
          qmake APP_TEST=0 ${{github.workspace}}/${{env.APP}}.pro
          make -j$(nproc)

      - name: deploy
        run: |
          mkdir -p ${{github.workspace}}/build/output
          cd ${{github.workspace}}/build/output
          cp ${{github.workspace}}/build/release/${{env.APP}} ${{github.workspace}}/build/output/

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.APP}}_${{env.APP_TIME}}_${{env.APP_SHA1}}_${{github.run_number}}
          path: |
            ${{github.workspace}}/build/test/log/*.log
            ${{github.workspace}}/build/output/
