# Qt 自动化编译

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  APP: tx

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.11"
          host: "linux"
          target: "desktop"
          cached: "${{ steps.cache-qt.outputs.cache-hit }}"
          setup-python: "true"

      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build/test
          cd ${GITHUB_WORKSPACE}/build/test
          qmake APP_TEST=1 ${GITHUB_WORKSPACE}/${APP}.pro
          make -j$(nproc)
          make check

      - name: build release
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build/release
          cd ${GITHUB_WORKSPACE}/build/release
          qmake APP_TEST=0 ${GITHUB_WORKSPACE}/${APP}.pro
          make -j$(nproc)

      - name: deploy
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build/output
          cd ${GITHUB_WORKSPACE}/build/output
          cp ${GITHUB_WORKSPACE}/build/release/${APP} ${GITHUB_WORKSPACE}/build/output/
          cp ${GITHUB_WORKSPACE}/build/test/log/*.log ${GITHUB_WORKSPACE}/build/output/

      - run: |
          tree -L 3 -h ${GITHUB_WORKSPACE}

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${APP}_$(date -u  +%Y%m%d%H%M%S)
          path: |
            ${{github.workspace}}/build/test/log/*.log
            ${{github.workspace}}/build/output/
