# Qt 自动化编译

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  APP: tx

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: "5.12.11"
          host: "linux"
          target: "desktop"
          cached: "${{ steps.cache-qt.outputs.cache-hit }}"
          setup-python: "true"

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          mkdir ${GITHUB_WORKSPACE}/../build
          cd ${GITHUB_WORKSPACE}/../build
          qmake ${GITHUB_WORKSPACE}/tx.pro
          make -j$(nproc)

      - name: test
        run: |
          mkdir ${GITHUB_WORKSPACE}/../build
          cd ${GITHUB_WORKSPACE}/../build
          qmake ${GITHUB_WORKSPACE}/tx.pro
          make -j$(nproc)
