# Qt 自动化编译

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: "5.12.11"
          host: "linux"
          target: "desktop"
          dir: "${{ github.workspace }}/example/"
          install-deps: "true"
          cached: "false"
          setup-python: "true"

      - uses: actions/checkout@v2

      - name: build
        run: |
          ls -AFlh
          tree -h
